/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TimeArchiveInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchIds"
      | "batches"
      | "fileExists"
      | "fileIds"
      | "files"
      | "getBatch"
      | "getFile"
      | "getFileTags"
      | "getRecentFiles"
      | "getReputation"
      | "getStatistics"
      | "getTotalFiles"
      | "getUploaderFiles"
      | "owner"
      | "pause"
      | "paused"
      | "recordAccess"
      | "registerBatch"
      | "registerFile"
      | "renounceOwnership"
      | "totalBatches"
      | "totalFiles"
      | "totalStorage"
      | "transferOwnership"
      | "unpause"
      | "uploaderFiles"
      | "uploaderReputation"
      | "verifyExistence"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchRegistered"
      | "FileAccessed"
      | "FileRegistered"
      | "OwnershipTransferred"
      | "Paused"
      | "ReputationUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "batches", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "fileExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fileIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "files", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getBatch", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getFile", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getFileTags",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecentFiles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStatistics",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalFiles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUploaderFiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordAccess",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerBatch",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerFile",
    values: [BytesLike, string, BytesLike, BigNumberish, boolean, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalBatches",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalFiles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalStorage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "uploaderFiles",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "uploaderReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyExistence",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "batchIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "batches", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fileExists", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fileIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "files", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFileTags",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecentFiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStatistics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalFiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUploaderFiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerFile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalFiles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "uploaderFiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uploaderReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyExistence",
    data: BytesLike
  ): Result;
}

export namespace BatchRegisteredEvent {
  export type InputTuple = [
    batchId: BytesLike,
    merkleRoot: BytesLike,
    fileCount: BigNumberish,
    uploader: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    batchId: string,
    merkleRoot: string,
    fileCount: bigint,
    uploader: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    batchId: string;
    merkleRoot: string;
    fileCount: bigint;
    uploader: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileAccessedEvent {
  export type InputTuple = [
    fileId: BytesLike,
    accessor: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    fileId: string,
    accessor: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    fileId: string;
    accessor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileRegisteredEvent {
  export type InputTuple = [
    fileId: BytesLike,
    metadataCID: string,
    uploader: AddressLike,
    timestamp: BigNumberish,
    blockNumber: BigNumberish,
    contentHash: BytesLike
  ];
  export type OutputTuple = [
    fileId: string,
    metadataCID: string,
    uploader: string,
    timestamp: bigint,
    blockNumber: bigint,
    contentHash: string
  ];
  export interface OutputObject {
    fileId: string;
    metadataCID: string;
    uploader: string;
    timestamp: bigint;
    blockNumber: bigint;
    contentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [user: AddressLike, newReputation: BigNumberish];
  export type OutputTuple = [user: string, newReputation: bigint];
  export interface OutputObject {
    user: string;
    newReputation: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TimeArchive extends BaseContract {
  connect(runner?: ContractRunner | null): TimeArchive;
  waitForDeployment(): Promise<this>;

  interface: TimeArchiveInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  batches: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, string] & {
        merkleRoot: string;
        fileCount: bigint;
        timestamp: bigint;
        uploader: string;
      }
    ],
    "view"
  >;

  fileExists: TypedContractMethod<[_fileId: BytesLike], [boolean], "view">;

  fileIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  files: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, string, bigint, boolean, bigint] & {
        metadataCID: string;
        uploader: string;
        timestamp: bigint;
        blockNumber: bigint;
        contentHash: string;
        fileSize: bigint;
        encrypted: boolean;
        accessCount: bigint;
      }
    ],
    "view"
  >;

  getBatch: TypedContractMethod<
    [_batchId: BytesLike],
    [
      [string, bigint, bigint, string] & {
        merkleRoot: string;
        fileCount: bigint;
        timestamp: bigint;
        uploader: string;
      }
    ],
    "view"
  >;

  getFile: TypedContractMethod<
    [_fileId: BytesLike],
    [
      [string, string, bigint, bigint, string, bigint, boolean, bigint] & {
        metadataCID: string;
        uploader: string;
        timestamp: bigint;
        blockNumber: bigint;
        contentHash: string;
        fileSize: bigint;
        encrypted: boolean;
        accessCount: bigint;
      }
    ],
    "view"
  >;

  getFileTags: TypedContractMethod<[_fileId: BytesLike], [string[]], "view">;

  getRecentFiles: TypedContractMethod<
    [_count: BigNumberish],
    [string[]],
    "view"
  >;

  getReputation: TypedContractMethod<
    [_uploader: AddressLike],
    [bigint],
    "view"
  >;

  getStatistics: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _totalFiles: bigint;
        _totalBatches: bigint;
        _totalStorage: bigint;
      }
    ],
    "view"
  >;

  getTotalFiles: TypedContractMethod<[], [bigint], "view">;

  getUploaderFiles: TypedContractMethod<
    [_uploader: AddressLike],
    [string[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  recordAccess: TypedContractMethod<[_fileId: BytesLike], [void], "nonpayable">;

  registerBatch: TypedContractMethod<
    [_batchId: BytesLike, _merkleRoot: BytesLike, _fileCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerFile: TypedContractMethod<
    [
      _fileId: BytesLike,
      _metadataCID: string,
      _contentHash: BytesLike,
      _fileSize: BigNumberish,
      _encrypted: boolean,
      _tags: string[]
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  totalBatches: TypedContractMethod<[], [bigint], "view">;

  totalFiles: TypedContractMethod<[], [bigint], "view">;

  totalStorage: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  uploaderFiles: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  uploaderReputation: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  verifyExistence: TypedContractMethod<
    [_fileId: BytesLike],
    [
      [boolean, bigint, bigint] & {
        exists: boolean;
        timestamp: bigint;
        blockNumber: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "batches"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, string] & {
        merkleRoot: string;
        fileCount: bigint;
        timestamp: bigint;
        uploader: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fileExists"
  ): TypedContractMethod<[_fileId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "fileIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "files"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, string, bigint, boolean, bigint] & {
        metadataCID: string;
        uploader: string;
        timestamp: bigint;
        blockNumber: bigint;
        contentHash: string;
        fileSize: bigint;
        encrypted: boolean;
        accessCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBatch"
  ): TypedContractMethod<
    [_batchId: BytesLike],
    [
      [string, bigint, bigint, string] & {
        merkleRoot: string;
        fileCount: bigint;
        timestamp: bigint;
        uploader: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFile"
  ): TypedContractMethod<
    [_fileId: BytesLike],
    [
      [string, string, bigint, bigint, string, bigint, boolean, bigint] & {
        metadataCID: string;
        uploader: string;
        timestamp: bigint;
        blockNumber: bigint;
        contentHash: string;
        fileSize: bigint;
        encrypted: boolean;
        accessCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFileTags"
  ): TypedContractMethod<[_fileId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRecentFiles"
  ): TypedContractMethod<[_count: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getReputation"
  ): TypedContractMethod<[_uploader: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStatistics"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _totalFiles: bigint;
        _totalBatches: bigint;
        _totalStorage: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalFiles"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUploaderFiles"
  ): TypedContractMethod<[_uploader: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "recordAccess"
  ): TypedContractMethod<[_fileId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerBatch"
  ): TypedContractMethod<
    [_batchId: BytesLike, _merkleRoot: BytesLike, _fileCount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerFile"
  ): TypedContractMethod<
    [
      _fileId: BytesLike,
      _metadataCID: string,
      _contentHash: BytesLike,
      _fileSize: BigNumberish,
      _encrypted: boolean,
      _tags: string[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalBatches"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalFiles"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalStorage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "uploaderFiles"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "uploaderReputation"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyExistence"
  ): TypedContractMethod<
    [_fileId: BytesLike],
    [
      [boolean, bigint, bigint] & {
        exists: boolean;
        timestamp: bigint;
        blockNumber: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "BatchRegistered"
  ): TypedContractEvent<
    BatchRegisteredEvent.InputTuple,
    BatchRegisteredEvent.OutputTuple,
    BatchRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "FileAccessed"
  ): TypedContractEvent<
    FileAccessedEvent.InputTuple,
    FileAccessedEvent.OutputTuple,
    FileAccessedEvent.OutputObject
  >;
  getEvent(
    key: "FileRegistered"
  ): TypedContractEvent<
    FileRegisteredEvent.InputTuple,
    FileRegisteredEvent.OutputTuple,
    FileRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BatchRegistered(bytes32,bytes32,uint256,address,uint256)": TypedContractEvent<
      BatchRegisteredEvent.InputTuple,
      BatchRegisteredEvent.OutputTuple,
      BatchRegisteredEvent.OutputObject
    >;
    BatchRegistered: TypedContractEvent<
      BatchRegisteredEvent.InputTuple,
      BatchRegisteredEvent.OutputTuple,
      BatchRegisteredEvent.OutputObject
    >;

    "FileAccessed(bytes32,address,uint256)": TypedContractEvent<
      FileAccessedEvent.InputTuple,
      FileAccessedEvent.OutputTuple,
      FileAccessedEvent.OutputObject
    >;
    FileAccessed: TypedContractEvent<
      FileAccessedEvent.InputTuple,
      FileAccessedEvent.OutputTuple,
      FileAccessedEvent.OutputObject
    >;

    "FileRegistered(bytes32,string,address,uint256,uint256,bytes32)": TypedContractEvent<
      FileRegisteredEvent.InputTuple,
      FileRegisteredEvent.OutputTuple,
      FileRegisteredEvent.OutputObject
    >;
    FileRegistered: TypedContractEvent<
      FileRegisteredEvent.InputTuple,
      FileRegisteredEvent.OutputTuple,
      FileRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ReputationUpdated(address,uint256)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
